from __future__ import annotations

from copy import deepcopy
from typing import Any

PROFILES: dict[str, dict[str, Any]] = {
    "爱你": {
        "description": "手势要甜，拍点要脆，点到就收。",
        "feed_caption": "甜妹感不是甩大，是每一下都刚好。",
        "pause_guides": [
            {
                "until_ratio": 0.34,
                "phase": "手势开机",
                "likely_stuck_at": "手先营业，胯晚点上线。",
                "watch_for": "口令：手到，胯到。",
                "suggested_focus": "upper",
                "metric": "timing",
                "body_part": "双手",
            },
            {
                "until_ratio": 0.67,
                "phase": "副歌上糖",
                "likely_stuck_at": "甜不是甩大，点到就收。",
                "watch_for": "口令：点、收、换边。",
                "suggested_focus": "upper",
                "metric": "trajectory",
                "body_part": "双手",
            },
            {
                "until_ratio": 1.0,
                "phase": "收尾定点",
                "likely_stuck_at": "笑容可以松，拍子不能掉。",
                "watch_for": "口令：停住半拍。",
                "suggested_focus": "upper",
                "metric": "angle",
                "body_part": "双臂",
            },
        ],
        "tutorials": [
            {
                "id": "aini-mirror",
                "title": "镜像跟跳｜左右别烧脑",
                "url": "",
                "error_type": "timing",
                "body_part": "双手",
                "description": "照镜子抄作业，手到再上胯。",
                "view_type": "镜像跟跳",
                "creator": "@动作搜索",
                "clip_seconds": "11 秒",
                "tags": ["upper", "timing"],
            },
            {
                "id": "aini-hands",
                "title": "手势慢放｜点到就收",
                "url": "",
                "error_type": "trajectory",
                "body_part": "双手",
                "description": "只看手，甜度别开过头。",
                "view_type": "手势慢放",
                "creator": "@动作搜索",
                "clip_seconds": "9 秒",
                "tags": ["upper", "trajectory"],
            },
            {
                "id": "aini-chorus",
                "title": "副歌口令｜手到、胯到",
                "url": "",
                "error_type": "timing",
                "body_part": "躯干",
                "description": "跟口令走，不用数拍数到宕机。",
                "view_type": "副歌口令",
                "creator": "@动作搜索",
                "clip_seconds": "8 秒",
                "tags": ["upper", "timing"],
            },
        ],
    },
    "科目三": {
        "description": "脚下点火、重心换挡，落地还得弹。",
        "feed_caption": "脚在蹦迪，重心可别还在加载。",
        "pause_guides": [
            {
                "until_ratio": 0.34,
                "phase": "脚步点火",
                "likely_stuck_at": "脚在蹦迪，重心还在加载。",
                "watch_for": "口令：点地，跟重心。",
                "suggested_focus": "lower",
                "metric": "timing",
                "body_part": "双脚",
            },
            {
                "until_ratio": 0.67,
                "phase": "摆胯换挡",
                "likely_stuck_at": "胯别画大饼，换边要脆。",
                "watch_for": "口令：左、右、秒切。",
                "suggested_focus": "lower",
                "metric": "trajectory",
                "body_part": "髋部",
            },
            {
                "until_ratio": 1.0,
                "phase": "弹回收步",
                "likely_stuck_at": "落地别坐死，弹回来。",
                "watch_for": "口令：落、弹、收。",
                "suggested_focus": "lower",
                "metric": "angle",
                "body_part": "双腿",
            },
        ],
        "tutorials": [
            {
                "id": "kemusan-feet",
                "title": "脚步俯拍｜脚往哪儿藏不住",
                "url": "",
                "error_type": "trajectory",
                "body_part": "双脚",
                "description": "只看落点，拒绝脚下玄学。",
                "view_type": "脚步俯拍",
                "creator": "@动作搜索",
                "clip_seconds": "10 秒",
                "tags": ["lower", "trajectory"],
            },
            {
                "id": "kemusan-slow",
                "title": "0.5×拆腿｜换边别排队",
                "url": "",
                "error_type": "timing",
                "body_part": "双腿",
                "description": "把腿和重心的先后拆开。",
                "view_type": "0.5×拆腿",
                "creator": "@动作搜索",
                "clip_seconds": "13 秒",
                "tags": ["lower", "timing"],
            },
            {
                "id": "kemusan-beat",
                "title": "重拍口令｜点、换、弹",
                "url": "",
                "error_type": "timing",
                "body_part": "双脚",
                "description": "跟三个字走，少开脑内会议。",
                "view_type": "重拍口令",
                "creator": "@动作搜索",
                "clip_seconds": "8 秒",
                "tags": ["lower", "timing"],
            },
        ],
    },
    "摇一摇": {
        "description": "肩胯一起联网，摇得松但轴心不跑。",
        "feed_caption": "摇不是散架，松弛感也有主心骨。",
        "pause_guides": [
            {
                "until_ratio": 0.34,
                "phase": "肩膀开机",
                "likely_stuck_at": "肩开机了，胯还没联网。",
                "watch_for": "口令：肩带胯。",
                "suggested_focus": "upper",
                "metric": "timing",
                "body_part": "双肩",
            },
            {
                "until_ratio": 0.67,
                "phase": "左右换边",
                "likely_stuck_at": "摇不是散架，轴心别跑路。",
                "watch_for": "口令：摇两边，人留中间。",
                "suggested_focus": "auto",
                "metric": "trajectory",
                "body_part": "躯干",
            },
            {
                "until_ratio": 1.0,
                "phase": "回正收尾",
                "likely_stuck_at": "回正要收，别把惯性带回家。",
                "watch_for": "口令：摇、停、回中。",
                "suggested_focus": "auto",
                "metric": "angle",
                "body_part": "躯干",
            },
        ],
        "tutorials": [
            {
                "id": "shake-upper",
                "title": "上身特写｜肩先带路",
                "url": "",
                "error_type": "timing",
                "body_part": "双肩",
                "description": "只看肩胯怎么一起联网。",
                "view_type": "上身特写",
                "creator": "@动作搜索",
                "clip_seconds": "9 秒",
                "tags": ["upper", "timing"],
            },
            {
                "id": "shake-beat",
                "title": "节奏口令｜摇、停、回中",
                "url": "",
                "error_type": "timing",
                "body_part": "躯干",
                "description": "三字口令，把惯性管住。",
                "view_type": "节奏口令",
                "creator": "@动作搜索",
                "clip_seconds": "8 秒",
                "tags": ["timing"],
            },
            {
                "id": "shake-mirror",
                "title": "镜像跟摇｜轴心别跑路",
                "url": "",
                "error_type": "trajectory",
                "body_part": "躯干",
                "description": "左右可以摇，人得留在中间。",
                "view_type": "镜像跟摇",
                "creator": "@动作搜索",
                "clip_seconds": "11 秒",
                "tags": ["trajectory"],
            },
        ],
    },
    "jumpstyle": {
        "description": "腿快、点准、落地还能接着弹。",
        "feed_caption": "腿像弹幕一样刷过去，落地还得稳。",
        "pause_guides": [
            {
                "until_ratio": 0.34,
                "phase": "踢腿点火",
                "likely_stuck_at": "腿是弹幕，落地得卡点。",
                "watch_for": "口令：踢、落、弹。",
                "suggested_focus": "lower",
                "metric": "timing",
                "body_part": "右腿",
            },
            {
                "until_ratio": 0.67,
                "phase": "前后换腿",
                "likely_stuck_at": "换腿别排队，前后脚要秒切。",
                "watch_for": "口令：前脚走，后脚到。",
                "suggested_focus": "lower",
                "metric": "trajectory",
                "body_part": "双腿",
            },
            {
                "until_ratio": 1.0,
                "phase": "落地续航",
                "likely_stuck_at": "脚别焊地上，落下就弹走。",
                "watch_for": "口令：轻落，快弹。",
                "suggested_focus": "lower",
                "metric": "angle",
                "body_part": "双腿",
            },
        ],
        "tutorials": [
            {
                "id": "jumpstyle-feet",
                "title": "脚下特写｜踢、落、弹",
                "url": "",
                "error_type": "timing",
                "body_part": "右腿",
                "description": "只看脚，别让上半身抢戏。",
                "view_type": "脚下特写",
                "creator": "@动作搜索",
                "clip_seconds": "10 秒",
                "tags": ["lower", "timing"],
            },
            {
                "id": "jumpstyle-slow",
                "title": "超慢换腿｜前后脚秒切",
                "url": "",
                "error_type": "timing",
                "body_part": "双腿",
                "description": "把换腿那一下掰开看。",
                "view_type": "超慢换腿",
                "creator": "@动作搜索",
                "clip_seconds": "12 秒",
                "tags": ["lower", "timing"],
            },
            {
                "id": "jumpstyle-beat",
                "title": "落地节拍｜轻落、快弹",
                "url": "",
                "error_type": "trajectory",
                "body_part": "双腿",
                "description": "听落点，不背论文。",
                "view_type": "落地节拍",
                "creator": "@动作搜索",
                "clip_seconds": "9 秒",
                "tags": ["lower", "trajectory"],
            },
        ],
    }
}


def with_coaching_profile(action: dict[str, Any]) -> dict[str, Any]:
    """Return an action with its named coaching personality applied."""

    profile = PROFILES.get(str(action.get("name", "")).strip().casefold())
    if profile is None:
        return action
    return {**action, **deepcopy(profile)}
